@server = https://studious-bassoon-qwggg74rgjqf49gg-8080.app.github.dev
@juegos = {{server}}/api/juegos
@jugadores = {{server}}/api/jugadores
###
GET {{juegos}}
###
POST {{juegos}}
Content-Type: application/json

{
    "nombre": "Pepsiman",
    "categoria": "No se",
    "descripcion": "Juego de la infancia"
}
###
POST {{jugadores}}
Content-Type: application/json

{"nombre": "Otro Jugador"}
###
GET {{server}}/api/integrantes/1/juego
###
GET {{server}}/api/equipos/1/formacion